/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as rwardTokenSol from "./RwardToken.sol";
export type { rwardTokenSol };
export type { StakeToken } from "./StakeToken";
export type { Staking } from "./Staking";
