/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IInitializable,
  IInitializableInterface,
} from "../../../contracts/G_Upgradable_NFT/IInitializable";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes[]",
        name: "",
        type: "bytes[]",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): IInitializableInterface {
    return new utils.Interface(_abi) as IInitializableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IInitializable {
    return new Contract(address, _abi, signerOrProvider) as IInitializable;
  }
}
