/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TestCoordinator } from "./TestCoordinator";
export type { VRFConsumerBase } from "./VRFConsumerBase";
