/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testCoordinatorSol from "./TestCoordinator.sol";
export type { testCoordinatorSol };
export type { CoinFlipper } from "./CoinFlipper";
