/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface EIP712XInterface extends utils.Interface {
  functions: {
    "MESSAGE_TYPE_HASH()": FunctionFragment;
    "buildDomainHash(bytes32,bytes32,uint256,address)": FunctionFragment;
    "buildStructHash(address,uint256,uint256,uint256)": FunctionFragment;
    "changeDomain(string,string,uint256,address)": FunctionFragment;
    "getCurrentDomainHash()": FunctionFragment;
    "getDomainHash(uint256)": FunctionFragment;
    "getPrefixedDataHash(bytes32)": FunctionFragment;
    "getTypedDataHash(bytes32)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerDomain(string,string,uint256,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "validDomainHash(uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "MESSAGE_TYPE_HASH"
      | "buildDomainHash"
      | "buildStructHash"
      | "changeDomain"
      | "getCurrentDomainHash"
      | "getDomainHash"
      | "getPrefixedDataHash"
      | "getTypedDataHash"
      | "owner"
      | "registerDomain"
      | "renounceOwnership"
      | "transferOwnership"
      | "validDomainHash"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "MESSAGE_TYPE_HASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buildDomainHash",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "buildStructHash",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "changeDomain",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentDomainHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDomainHash",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrefixedDataHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTypedDataHash",
    values: [PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDomain",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "validDomainHash",
    values: [PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(
    functionFragment: "MESSAGE_TYPE_HASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildDomainHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "buildStructHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentDomainHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDomainHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrefixedDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTypedDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "validDomainHash",
    data: BytesLike
  ): Result;

  events: {
    "DomainChanged(string,string,uint256,address)": EventFragment;
    "DomainRegistered(string,string,uint256,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DomainChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DomainRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface DomainChangedEventObject {
  name: string;
  version: string;
  chainId: BigNumber;
  targetContract: string;
}
export type DomainChangedEvent = TypedEvent<
  [string, string, BigNumber, string],
  DomainChangedEventObject
>;

export type DomainChangedEventFilter = TypedEventFilter<DomainChangedEvent>;

export interface DomainRegisteredEventObject {
  name: string;
  version: string;
  chainId: BigNumber;
  targetContract: string;
}
export type DomainRegisteredEvent = TypedEvent<
  [string, string, BigNumber, string],
  DomainRegisteredEventObject
>;

export type DomainRegisteredEventFilter =
  TypedEventFilter<DomainRegisteredEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface EIP712X extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: EIP712XInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    MESSAGE_TYPE_HASH(overrides?: CallOverrides): Promise<[string]>;

    buildDomainHash(
      _name: PromiseOrValue<BytesLike>,
      _version: PromiseOrValue<BytesLike>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    buildStructHash(
      _receiver: PromiseOrValue<string>,
      _receivingChainId: PromiseOrValue<BigNumberish>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    changeDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getCurrentDomainHash(overrides?: CallOverrides): Promise<[string]>;

    getDomainHash(
      _chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPrefixedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTypedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    registerDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    validDomainHash(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  MESSAGE_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

  buildDomainHash(
    _name: PromiseOrValue<BytesLike>,
    _version: PromiseOrValue<BytesLike>,
    _chainId: PromiseOrValue<BigNumberish>,
    _verifier: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  buildStructHash(
    _receiver: PromiseOrValue<string>,
    _receivingChainId: PromiseOrValue<BigNumberish>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _nonce: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  changeDomain(
    _name: PromiseOrValue<string>,
    _version: PromiseOrValue<string>,
    _chainId: PromiseOrValue<BigNumberish>,
    _verifier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getCurrentDomainHash(overrides?: CallOverrides): Promise<string>;

  getDomainHash(
    _chainId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  getPrefixedDataHash(
    _structHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTypedDataHash(
    _structHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  registerDomain(
    _name: PromiseOrValue<string>,
    _version: PromiseOrValue<string>,
    _chainId: PromiseOrValue<BigNumberish>,
    _verifier: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  validDomainHash(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    MESSAGE_TYPE_HASH(overrides?: CallOverrides): Promise<string>;

    buildDomainHash(
      _name: PromiseOrValue<BytesLike>,
      _version: PromiseOrValue<BytesLike>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    buildStructHash(
      _receiver: PromiseOrValue<string>,
      _receivingChainId: PromiseOrValue<BigNumberish>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    changeDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getCurrentDomainHash(overrides?: CallOverrides): Promise<string>;

    getDomainHash(
      _chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    getPrefixedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTypedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    registerDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    validDomainHash(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "DomainChanged(string,string,uint256,address)"(
      name?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null,
      chainId?: null,
      targetContract?: null
    ): DomainChangedEventFilter;
    DomainChanged(
      name?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null,
      chainId?: null,
      targetContract?: null
    ): DomainChangedEventFilter;

    "DomainRegistered(string,string,uint256,address)"(
      name?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null,
      chainId?: null,
      targetContract?: null
    ): DomainRegisteredEventFilter;
    DomainRegistered(
      name?: PromiseOrValue<string> | null,
      version?: PromiseOrValue<string> | null,
      chainId?: null,
      targetContract?: null
    ): DomainRegisteredEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    MESSAGE_TYPE_HASH(overrides?: CallOverrides): Promise<BigNumber>;

    buildDomainHash(
      _name: PromiseOrValue<BytesLike>,
      _version: PromiseOrValue<BytesLike>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buildStructHash(
      _receiver: PromiseOrValue<string>,
      _receivingChainId: PromiseOrValue<BigNumberish>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    changeDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getCurrentDomainHash(overrides?: CallOverrides): Promise<BigNumber>;

    getDomainHash(
      _chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPrefixedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTypedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    registerDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    validDomainHash(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MESSAGE_TYPE_HASH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buildDomainHash(
      _name: PromiseOrValue<BytesLike>,
      _version: PromiseOrValue<BytesLike>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buildStructHash(
      _receiver: PromiseOrValue<string>,
      _receivingChainId: PromiseOrValue<BigNumberish>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _nonce: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    changeDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getCurrentDomainHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDomainHash(
      _chainId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPrefixedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTypedDataHash(
      _structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerDomain(
      _name: PromiseOrValue<string>,
      _version: PromiseOrValue<string>,
      _chainId: PromiseOrValue<BigNumberish>,
      _verifier: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    validDomainHash(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
