/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as imxBridgeSol from "./IMX_Bridge.sol";
export type { imxBridgeSol };
export type { IMX } from "./IMX";
export type { IMintable } from "./IMintable";
export type { Mintable } from "./Mintable";
