// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bodyContainer': string;
  'bodyGrid': string;
  'buttonCancel': string;
  'buttonMT': string;
  'buttonWC': string;
  'header': string;
  'headerTitle': string;
  'login': string;
  'modalBox': string;
  'modalDesc': string;
  'modalGroupButton': string;
  'modalIcon': string;
  'modalTitle': string;
  'navItem': string;
  'navbar': string;
  'titleRight': string;
  'titleSpan': string;
}
export const cssExports: CssExports;
export default cssExports;
