/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as testCoordinatorSol from "./TestCoordinator.sol";
export { CoinFlipper__factory } from "./CoinFlipper__factory";
