/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Mintable,
  MintableInterface,
} from "../../../../contracts/G_Upgradable_NFT/IMXBridge/Mintable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "blueprint",
        type: "bytes",
      },
    ],
    name: "AssetMinted",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "quantity",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "mintingBlob",
        type: "bytes",
      },
    ],
    name: "mintFor",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Mintable__factory {
  static readonly abi = _abi;
  static createInterface(): MintableInterface {
    return new utils.Interface(_abi) as MintableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Mintable {
    return new Contract(address, _abi, signerOrProvider) as Mintable;
  }
}
